version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/simplewebapp"
    schedule:
      interval: "weekly"

  - package-ecosystem: "maven"
    directory: "/gymplus-booker-v1"
    schedule:
      interval: "weekly"

  - package-ecosystem: "maven"
    directory: "/spring-cloud"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

