spring.application.name=taco-order-service
# PostgreSQL (driver auto-detected from URL)

# PostgreSQL JDBC URL (AWS RDS)
spring.datasource.url=jdbc:postgresql://taco-postgres-db.c25usmiwaa3k.us-east-1.rds.amazonaws.com:5432/taco_order_db

# PostgreSQL credentials
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

# JPA / Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9000/realms/learning

server.port=8082

eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka/}


