spring.application.name=taco-order-service
# Oracle JDBC driver
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# Oracle JDBC URL
# For SID-based connection
#spring.datasource.url=jdbc:oracle:thin:@localhost:1521:gsp

# OR (recommended) Service Name?based connection
 spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/ORCLPDB1

# Oracle credentials
spring.datasource.username=TACO_ORDER_SCHEMA
spring.datasource.password=${DB_PASSWORD}

# JPA / Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

#spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9000/realms/learning

server.port=8082

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/


