# Oracle JDBC driver
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# Oracle JDBC URL
# For SID-based connection
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:gsp

# OR (recommended) Service Name?based connection
# spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/ORCLPDB1

# Oracle credentials
spring.datasource.username=GSP
spring.datasource.password=${DB_PASSWORD}

# JPA / Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
